print('-----------------------')
a = input('Masukkan nilai: ')
print(a)
print(type(a))
print('-----------------------')
b = eval(input('Masukkan nilai: '))
print(b)
print(type(b))
print('-----------------------')
#c = int(input('Masukkan nilai: '))
c = float(input('Masukkan nilai: '))
print(c)
print(type(c))